DROP TABLE IF EXISTS Pet;
CREATE TABLE Pet(petId SERIAL PRIMARY KEY, petType VARCHAR(255), petName VARCHAR(255), petAge INT);

DROP TABLE IF EXISTS PetType;
CREATE TABLE PetType(id SERIAL PRIMARY KEY, petType VARCHAR(255));