version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  petstore:
    container_name: petstore
    image: thisaramj/petstore
    ports:
      - "8080:8080"
    restart: always
    links:
      - postgresql

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=petstoredb
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always

  grafana:
    image: grafana/grafana:7.0.3
    user: "472"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./src:/var/lib/grafana/dashboards
    restart: always

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always